### ISSUE TITLE
RSpec Failures in QuestionnairesController#add_new_questions

### ISSUE THREAD

**Issue by nnhimes** [BoergerJ/expertiza#26]
```
Failures:
  1) QuestionnairesController#add_new_questions when adding ScoredQuestion redirects to questionnaires#edit page after adding new questions
     Failure/Error: question_ids = Questionnaire.find(questionnaire_id).questions.ids
     NoMethodError:
       undefined method `ids' for [#<Double "Criterion">]:Array
     # ./app/controllers/questionnaires_controller.rb:187:in `add_new_questions'
     # ./spec/controllers/questionnaires_controller_spec.rb:403:in `block (4 levels) in <top (required)>'
  2) QuestionnairesController#add_new_questions when adding unScoredQuestion redirects to questionnaires#edit page after adding new questions
     Failure/Error: question_ids = Questionnaire.find(questionnaire_id).questions.ids
     NoMethodError:
       undefined method `ids' for [#<Double "Dropdown">]:Array
     # ./app/controllers/questionnaires_controller.rb:187:in `add_new_questions'
     # ./spec/controllers/questionnaires_controller_spec.rb:416:in `block (4 levels) in <top (required)>'
```

**Comment by suryamak** [comment]
potential fix https://stackoverflow.com/a/34142633
